version: '3.8'

services:
  pyspark:
    build: .
    container_name: pyspark-jupyter
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./work:/home/jovyan/work
    env_file:                     # <-- NOWA SEKCJA
      - .env                      # <-- Wskazujemy nasz ukryty plik
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    user: root
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: local-postgres
    environment:                  #Database Credencials
      - POSTGRES_USER=admin       
      - POSTGRES_PASSWORD=admin   
      - POSTGRES_DB=Warsaw_Bus_DB    
    ports:
      - "5432:5432"               
    volumes:
      - pgdata:/var/lib/postgresql/data  # Zapisuje dane bazy trwale na dysku

volumes:
  pgdata:  # Definicja wolumenu dla Postgresa  